[package]
name = "test-client"
version = "0.2.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
publish = false

[features]
mock = [
    "sunshine-client-utils/mock",
]

[dependencies]
async-trait = "0.1.40"
libipld = { version = "0.6.1", default-features = false }
substrate-subxt = "0.12.0"
sunshine-chain-client = { path = "../../chain/client" }
sunshine-client-utils = { git = "https://github.com/sunshine-protocol/sunshine-core" }
sunshine-faucet-client = { path = "../../faucet/client" }
sunshine-identity-client = { path = "../../identity/client" }
test-node = { path = "../node" }
